# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('subset', models.IntegerField()),
                ('counts', models.IntegerField()),
                ('yard_line', models.IntegerField()),
                ('side', models.IntegerField()),
                ('x', models.FloatField()),
                ('hash_line', models.CharField(choices=[('FH', 'Front Hash'), ('BH', 'Back Hash'), ('FS', 'Front Sideline'), ('BS', 'Back Sideline')], max_length=2)),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Show'),
        ),
    ]
